name: project_fatiha
description: Project Fatiha

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pictures/
  fonts:
    - family: Mothanna
      fonts:
        - asset: assets/fonts/mothanna.ttf
    - family: Sanfcancisco
      fonts:
        - asset: assets/fonts/sanfcancisco.ttf