name: project_fatiha
description: Project Fatiha

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_html: ^2.2.1
  custom_sliding_segmented_control: ^1.7.2
  screenshot: ^1.2.3
  share_plus: ^4.1.0
  wakelock: ^0.6.2
  clipboard: ^0.1.3
  just_audio: ^0.9.28
  hive_flutter: ^1.1.0
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/pictures/
    - assets/databases/
  fonts:
    - family: Mothanna
      fonts:
        - asset: assets/fonts/mothanna.ttf
    - family: Aqum
      fonts:
        - asset: assets/fonts/aqum_two.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/quran.ttf