name: project_fatiha
description: Project Fatiha

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_html: ^2.2.1
  custom_sliding_segmented_control: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pictures/
  fonts:
    - family: Mothanna
      fonts:
        - asset: assets/fonts/mothanna.ttf
    - family: Aqum
      fonts:
        - asset: assets/fonts/aqum_two.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/quran.ttf